module.exports = {
    
    frequencia_dos_numeros: {
        intervalo: [
            {
                umDia: [
                    { value:0, number:1 },
                    { value:0, number:2  },
                    { value:0, number:3  },
                    { value:0, number:4  },
                    { value:0, number:5  },
                    { value:0, number:6  },
                    { value:0, number:7  },
                    { value:0, number:8  },
                    { value:0, number:9  },
                    { value:0, number:10 },
                    { value:0, number:11  },
                    { value:0, number:12  },
                    { value:0, number:13  },
                    { value:0, number:14  },
                    { value:0, number:15  },
                    { value:0, number:16  },
                    { value:0, number:17  },
                    { value:0, number:18  },
                    { value:0, number:19  },
                    { value:0, number:20  },
                    { value:0, number:21  },
                    { value:0, number:22  },
                    { value:0, number:23  },
                    { value:0, number:24  },
                    { value:0, number:25  }
                ]
            },
            {
                doisDias: [
                    { value:0, number:1 },
                    { value:0, number:2  },
                    { value:0, number:3  },
                    { value:0, number:4  },
                    { value:0, number:5  },
                    { value:0, number:6  },
                    { value:0, number:7  },
                    { value:0, number:8  },
                    { value:0, number:9  },
                    { value:0, number:10 },
                    { value:0, number:11  },
                    { value:0, number:12  },
                    { value:0, number:13  },
                    { value:0, number:14  },
                    { value:0, number:15  },
                    { value:0, number:16  },
                    { value:0, number:17  },
                    { value:0, number:18  },
                    { value:0, number:19  },
                    { value:0, number:20  },
                    { value:0, number:21  },
                    { value:0, number:22  },
                    { value:0, number:23  },
                    { value:0, number:24  },
                    { value:0, number:25  }
                ]
            },
            {
                tresDias: [
                    { value:0, number:1 },
                    { value:0, number:2  },
                    { value:0, number:3  },
                    { value:0, number:4  },
                    { value:0, number:5  },
                    { value:0, number:6  },
                    { value:0, number:7  },
                    { value:0, number:8  },
                    { value:0, number:9  },
                    { value:0, number:10 },
                    { value:0, number:11  },
                    { value:0, number:12  },
                    { value:0, number:13  },
                    { value:0, number:14  },
                    { value:0, number:15  },
                    { value:0, number:16 },
                    { value:0, number:17  },
                    { value:0, number:18  },
                    { value:0, number:19  },
                    { value:0, number:20  },
                    { value:0, number:21  },
                    { value:0, number:22  },
                    { value:0, number:23  },
                    { value:0, number:24  },
                    { value:0, number:25  }
                ]
            },
            {
                quatroDias: [
                    { value:0, number:1 },
                    { value:0, number:2  },
                    { value:0, number:3  },
                    { value:0, number:4  },
                    { value:0, number:5  },
                    { value:0, number:6  },
                    { value:0, number:7  },
                    { value:0, number:8  },
                    { value:0, number:9  },
                    { value:0, number:10 },
                    { value:0, number:11  },
                    { value:0, number:12  },
                    { value:0, number:13  },
                    { value:0, number:14  },
                    { value:0, number:15  },
                    { value:0, number:16 },
                    { value:0, number:17  },
                    { value:0, number:18  },
                    { value:0, number:19  },
                    { value:0, number:20  },
                    { value:0, number:21  },
                    { value:0, number:22  },
                    { value:0, number:23  },
                    { value:0, number:24  },
                    { value:0, number:25  }
                ]
            },
            {
                cincoDias: [
                    { value:0, number:1 },
                    { value:0, number:2  },
                    { value:0, number:3  },
                    { value:0, number:4  },
                    { value:0, number:5  },
                    { value:0, number:6  },
                    { value:0, number:7  },
                    { value:0, number:8  },
                    { value:0, number:9  },
                    { value:0, number:10 },
                    { value:0, number:11  },
                    { value:0, number:12  },
                    { value:0, number:13  },
                    { value:0, number:14  },
                    { value:0, number:15  },
                    { value:0, number:16 },
                    { value:0, number:17  },
                    { value:0, number:18  },
                    { value:0, number:19  },
                    { value:0, number:20  },
                    { value:0, number:21  },
                    { value:0, number:22  },
                    { value:0, number:23  },
                    { value:0, number:24  },
                    { value:0, number:25  }
                ]
            },
            {
                seisDias: [
                    { value:0, number:1 },
                    { value:0, number:2  },
                    { value:0, number:3  },
                    { value:0, number:4  },
                    { value:0, number:5  },
                    { value:0, number:6  },
                    { value:0, number:7  },
                    { value:0, number:8  },
                    { value:0, number:9  },
                    { value:0, number:10 },
                    { value:0, number:11  },
                    { value:0, number:12  },
                    { value:0, number:13  },
                    { value:0, number:14  },
                    { value:0, number:15  },
                    { value:0, number:16 },
                    { value:0, number:17  },
                    { value:0, number:18  },
                    { value:0, number:19  },
                    { value:0, number:20  },
                    { value:0, number:21  },
                    { value:0, number:22  },
                    { value:0, number:23  },
                    { value:0, number:24  },
                    { value:0, number:25  }
                ]
            },
            {
                seteDias: [
                    { value:0, number:1 },
                    { value:0, number:2  },
                    { value:0, number:3  },
                    { value:0, number:4  },
                    { value:0, number:5  },
                    { value:0, number:6  },
                    { value:0, number:7  },
                    { value:0, number:8  },
                    { value:0, number:9  },
                    { value:0, number:10 },
                    { value:0, number:11  },
                    { value:0, number:12  },
                    { value:0, number:13  },
                    { value:0, number:14  },
                    { value:0, number:15  },
                    { value:0, number:16 },
                    { value:0, number:17  },
                    { value:0, number:18  },
                    { value:0, number:19  },
                    { value:0, number:20  },
                    { value:0, number:21  },
                    { value:0, number:22  },
                    { value:0, number:23  },
                    { value:0, number:24  },
                    { value:0, number:25  }
                ]
            },
        ]
    }
    
};